name: C/C++ CI

on:
  push:
    tags:
      - v*
      
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get install zlib1g-dev
        sudo apt-get install zlib1g
        sudo apt-get install libz-mingw-w64-dev
        sudo apt-get install libz-mingw-w64
        sudo apt-get install mingw-w64
        sudo apt-get install g++-mingw-w64-i686-posix
    - run: make
    - run: |
        mkdir -p release
        PROGRAMNAME="me3_csv_ekstraktor"
        VERSION="${GITHUB_REF_NAME#v}"
        cp build/me3_csv_ekstraktor_Linux "release/${PROGRAMNAME}-${VERSION}-Linux"
        make clean
        make TARGET_OS=windows
        cp build/me3_csv_ekstraktor_Win32.exe "release/${PROGRAMNAME}-${VERSION}-Win32"
     
    - name: Public
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*
